name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below to help us fix it.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Configure Neev with...
        2. Call method...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages or stack traces if applicable.
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      placeholder: "8.2"
    validations:
      required: true

  - type: input
    id: laravel-version
    attributes:
      label: Laravel Version
      placeholder: "11.0"
    validations:
      required: true

  - type: input
    id: neev-version
    attributes:
      label: Neev Version
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: database
    attributes:
      label: Database
      placeholder: MySQL 8.0 / PostgreSQL 16 / SQLite

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or relevant configuration.
